"""Add email_confirmed_at to User

Revision ID: 0bd452c26546
Revises: 2624847cb44a
Create Date: 2025-08-15 19:57:32.711581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd452c26546'
down_revision = '2624847cb44a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_email_confirmed_at'), ['email_confirmed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email_confirmed_at'))
        batch_op.drop_column('email_confirmed_at')

    # ### end Alembic commands ###
